# Generated by Django 5.1.2 on 2024-10-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('message_subject', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
            ],
        ),
    ]
